
language: node_js
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
- npm install -g hexo
before_script:
- git config --global user.name "$username"
- git config --global user.email "$email"
- sed -i'' "s~git@github.com:${username}/${username}.git~https://${password}:x-oauth-basic@github.com/${username}/${username}.git~" _config.yml
install:
- npm install
script:
- hexo generate -d
